services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=esportclash'
      - 'POSTGRES_PASSWORD=esportclash'
      - 'POSTGRES_USER=esportclash'
    ports:
      - '5432'
